API_TOKEN = "7402636958:AAEdQF221sx9u5TNyPNVn4mF5hDFl1z-wiI"
REDIS_HOST = "redis.railway.internal"
REDIS_PORT = 6379  
REDIS_PASSWORD = "yQiWGxBMTJWMFJWxYVLuBZXvlCLtMIOj"  
POSTGRES_URL = "postgresql://postgres:AxCymzjvzcXSDOMpQJgiNTmQzsGyKXdT@postgres.railway.internal:5432/railway"

print(f"REDIS_HOST={REDIS_HOST}, REDIS_PORT={REDIS_PORT}, REDIS_PASSWORD={'yes' if REDIS_PASSWORD else 'no'}, POSTGRES_URL={POSTGRES_URL}")
